FROM node:alpine

WORKDIR '/app'

COPY package.json .

RUN npm cache clean --force && \
    npm config set registry https://registry.npmjs.org/ && \
    echo "104.16.19.35 registry.npmjs.org" >> /etc/hosts && \
    npm install

#COPY . .

ENTRYPOINT "npm run test"